name: SQL
run-name: SQL Test
on: [push]
jobs:
  SQL-Test:
    runs-on: ubuntu-latest
    steps:

      - run: |
          sudo /etc/init.d/mysql start
          mysql -e 'SHOW DATABASES;' -uroot -proot      
